### ISSUE TITLE
release with python 3.7 support

### ISSUE THREAD

**Issue by xrmx** [snipsco/snips-nlu-utils#52]
Hello, from a quick search it looks snips-nlu-utils is blocking support for python3.7 in the upper layers of the snips pipeline. Any chance you can release a 0.8.0 please? Thanks in advance

**Comment by adrienball** [comment]
Hi @xrmx ,
Wheels for Python3.7 are now available for snips-nlu-utils >= 0.7.1
Python3.7 is now supported for snips-nlu >= 0.19.0

Cheers

**Comment by xrmx** [comment]
Thanks!
